#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -z "$PLUSHU_BUILDPACKS_DIR" ]]; then
  echo "No buildpacks dir defined; aborting." >&2
  exit 1
fi

i=`ls -f "$PLUSHU_BUILDPACKS_DIR" | wc -l`

for n in ruby nodejs clojure python java gradle grails scala play php go; do
  "$PLUSHU_ROOT/lib/plushook" install-buildpack \
    $(printf '%02i_heroku-buildpack-%s' "$i" "$n") \
    "https://github.com/heroku/heroku-buildpack-$n.git"
  i=$((i+1))
done
